import { NextRequest } from "next/server";
import fs from "fs";
import path from "path";

function withValidProperties(
  properties: Record<string, undefined | string | string[]>,
) {
  return Object.fromEntries(
    Object.entries(properties).filter(([key, value]) => {
      if (Array.isArray(value)) {
        return value.length > 0;
      }
      return !!value;
    }),
  );
}

export async function GET() {
  const URL = process.env.NEXT_PUBLIC_URL;

  // Try to serve the static manifest file first (generated by our scripts)
  const staticManifestPath = path.join(
    process.cwd(),
    "public",
    ".well-known",
    "farcaster.json",
  );

  if (fs.existsSync(staticManifestPath)) {
    try {
      const staticManifest = JSON.parse(
        fs.readFileSync(staticManifestPath, "utf8"),
      );
      return Response.json(staticManifest);
    } catch (error) {
      console.error(
        "Error reading static manifest, falling back to dynamic generation:",
        error,
      );
    }
  }

  // Fallback to dynamic generation (legacy behavior)
  return Response.json({
    accountAssociation: {
      header: process.env.FARCASTER_HEADER,
      payload: process.env.FARCASTER_PAYLOAD,
      signature: process.env.FARCASTER_SIGNATURE,
    },
    miniapp: withValidProperties({
      version: "1",
      name: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME || "DBRO Mini Temp",
      subtitle:
        process.env.NEXT_PUBLIC_APP_SUBTITLE ||
        "Stake your Mini Temp earn BIG!",
      description:
        process.env.NEXT_PUBLIC_APP_DESCRIPTION ||
        "Stake a max of 5M DBRO tokens, earn passively, high APY and access to exclusive utilities",
      screenshotUrls: [
        `${URL}/screenshot.png`,
        `${URL}/staking-2.png`,
        `${URL}/staking-3.png`,
      ],
      iconUrl:
        process.env.NEXT_PUBLIC_APP_ICON ||
        process.env.NEXT_PUBLIC_ICON_URL ||
        `${URL}/newIcon.jpg`,
      splashImageUrl:
        process.env.NEXT_PUBLIC_APP_SPLASH_IMAGE || `${URL}/newSplash.png`,
      splashBackgroundColor:
        process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR || "#000000",
      homeUrl: URL,
      webhookUrl: `${URL}/api/webhook`,
      primaryCategory:
        process.env.NEXT_PUBLIC_APP_PRIMARY_CATEGORY || "utility",
      tags: ["staking", "dbro", "rewards", "apy", "utilities"],
      heroImageUrl:
        process.env.NEXT_PUBLIC_APP_HERO_IMAGE || `${URL}/newHero.png`,
      tagline: process.env.NEXT_PUBLIC_APP_TAGLINE || "Mini Temp for the Bros",
      ogTitle:
        process.env.NEXT_PUBLIC_APP_OG_TITLE || "DBRO Mini Temp Passive Income",
      ogDescription:
        process.env.NEXT_PUBLIC_APP_OG_DESCRIPTION ||
        "Passive income starts with staking DBRO, Turn idle DBRO into daily rewards",
      ogImageUrl: process.env.NEXT_PUBLIC_APP_OG_IMAGE || `${URL}/newHero.png`,
      noindex: "true",
    }),
    baseBuilder: {
      allowedAddresses: ["0x1d0b2cfebabb59b3af59ff77def5397ce4be9e77"],
    },
  });
}
